//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 08:40:26 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        namespace = com.bkav.edoc.service.resource.StringPool.TARGET_NAMESPACE, xmlns = {@javax.xml.bind.annotation.XmlNs(prefix = "edXML",
        namespaceURI = com.bkav.edoc.service.resource.StringPool.TARGET_NAMESPACE)})
package com.bkav.edoc.service.xml.base.header;

