let app_message = {
    // config for data table header
    "table_header_subject": "Trích yếu",
    "table_header_fromOrgan": "Đơn vị gửi",
    "table_header_documentCate": "Loại",
    "table_header_createDate": "Ngày tạo",
    "table_header_code": "Số kí hiệu",
    "table_header_modify_date": "ModifyDate",
    "table_header_document_id": "DocumentId",
    "table_header_document_create": "CreateDate",
    //config for form edoc detail
    "message_no_data": "Không có dữ liệu",
    "edoc_table_header_subject": "Trích yếu",
    "edoc_table_header_fromOrgan": "Đơn vị gửi",
    "edoc_table_header_toOrgan": "Đơn vị nhận",
    "edoc_table_header_code": "Số kí hiệu",
    "edoc_table_header_documentCate": "Loại văn bản",
    "edoc_detail_priority": "Độ khẩn",
    "edoc_staff_name": "Người soạn",
    "edoc_page_amount": "Số bản",
    "edoc_page_number": "Số trang",
    "edoc_from_organ": "Đơn vị gửi",
    "edoc_date_publish": "Ngày BH",
    "edoc_signer_info": "Người ký",
    "edoc_deadline": "Hạn hồi báo",
    "no_data": "Không có dữ liệu",
    "edoc_range": "Phạm vi",
    "edoc_detail_content": "Nội dung",
    "edoc_attachment": "File đính kèm",
    "attachment_download": "Tải xuống",
    "edoc_trace": "Trạng thái văn bản",
    "edoc_received_message": "Đã nhận về hệ thống",
    "edoc_not_received_message": "Chưa nhận về hệ thống",
    "edoc_delete_document": "Xoá file đính kèm",
    "edoc_remove_document" : "Kết thúc văn bản",
    "edoc_download_all_attachment": "Tải xuống tất cả",
    "edoc_document_type": "Loại văn bản",
    "edoc_document_position": "Chức vụ",
    //Config edoc status value
    "edoc_status_arrived": "Đã đến",
    "edoc_status_refuse": "Từ chối tiếp nhận",
    "edoc_status_received": "Đã tiếp nhận",
    "edoc_status_assignment": "Phân công",
    "edoc_status_processing": "Đang xử lý",
    "edoc_status_finish": "Hoàn thành",
    "edoc_status_recover": "Lấy lại",
    "edoc_status_accept_recover": "Đồng ý lấy lại/ cập nhật văn bản",
    "edoc_status_refuse_recover": "Từ chối lấy lại/ cập nhật văn bản",
    "edoc_main_handler": "Người xử lý chính:",
    "edoc_handler_comment": "Ý kiến người xử lý chính:",
    "edoc_no_data" : "No data",
    // custom config
    "edoc_new_document": "new-document",
    "edoc_organ_name": "Tên đơn vị",
    "edoc_organ_sent": "Gửi",
    "edoc_organ_received": "Nhận",
    "edoc_organ_total": "Tổng số",
    "edoc_message_error_report": "Nhập ngày bắt đầu và ngày kết thúc để thống kê!",
    "edoc_message_error_report_date": "Ngày bắt đầu không được lớn hơn ngày kết thúc !",
    //Datatable setting
    "language": {
        "decimal": "",
        "emptyTable": "Không có dữ liệu",
        "info": "Hiển thị _START_ đến _END_ trong tổng số _TOTAL_ kết quả",
        "infoEmpty": "Hiển thị 0 đến 0 trong tổng số 0 kết quả",
        "infoFiltered": "(được lọc từ _MAX_ mục)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Hiển thị _MENU_ bản ghi",
        "loadingRecords": "&nbsp;",
        "processing": "<div class='spinner' id='loadingDiv'></div>",
        "search": "Tìm kiếm:",
        "zeroRecords": "Không tìm thấy dữ liệu",
        "paginate": {
            "first": "Đầu tiên",
            "last": "Cuối cùng",
            "next": "&raquo;",
            "previous": "&laquo;"
        },
        "aria": {
            "sortAscending": ": Hiển thị sắp xếp tăng dần",
            "sortDescending": ": Hiển thị sắp xếp giảm dần"
        }
    },
    // Custom message
    "edoc_delete_draft_success": "Xoá văn bản nháp thành công",
    "edoc_delete_draft_error": "Xoá văn bản nháp thất bại",
    "edoc_publish_document_success": "Phát hành văn bản thành công !",
    "edoc_save_draft_success": "Lưu văn bản nháp thành công !",
    "edoc_publish_document_error": "Phát hành văn bản thất bại !!!",
    "edoc_export_file_name": "Thống kê gửi nhận chi tiết",
    "edoc_validate_document_request_fail": "Dữ liệu văn bản không hợp lệ !",
    // public stat
    "edoc_before_content": "Đến tháng {0} đã trao đổi",
    "edoc_after_first_content": "văn bản qua mạng",
    "edoc_after_second_content": "giữa {0} đơn vị",
    "edoc_after_last_content": "(Tự động cập nhật lúc {0})",
    "edoc_report_filter": "Hiển thị kết quả thống kê trong khoảng: ",
    "edoc_report_default_filter": "Hiển thị kết quả thống đến: "
};

let user_message = {
    // Data table header
    "table_header_fullName": "Tên đầy đủ",
    "table_header_username": "Tên đăng nhập",
    "table_header_emailAddress": "Địa chỉ email",
    "table_header_organize": "Đơn vị",
    "table_header_status": "Trạng thái",
    // Config for user detail form
    "user_table_header_fullName": "Tên đầy đủ",
    "user_table_header_userName": "Tên đăng nhập",
    "user_table_header_email": "Địa chỉ email",
    "user_table_header_organize": "Đơn vị",
    "user_table_header_status": "Trạng thái",
    "user_table_header_status_1": "Đang hoạt động",
    "user_table_header_status_0": "Ngừng hoạt động",
    "user_last_login_time" : "Thời gian truy cập",
    "user_last_login_ip" : "Địa chỉ IP truy cập",
    "user_is_on_sso" : "Đồng bộ SSO",
    "user_is_on_sso_true" : "Đã đồng bộ",
    "user_is_on_sso_false" : "Chưa đồng bộ",
    "manage_remove_user": "Xóa người dùng",
    "manage_permission_user": "Phân quyền",
    "manage_edit_user": "Chỉnh sửa",
    "user_import_from_excel_success": "Nhập dữ liệu người dùng từ Excel thành công",
    "user_import_invalid_format_file": "Sai định dạng file",
    "user_import_from_excel_fail": "Nhập dữ liệu người dùng thất bại",
    "user_import_from_excel_conflic": "Dữ liệu bị trùng",
    "user_import_from_excel_invalid_column": "File có thông tin cột không đúng!",
    "user_export_to_excel_success": "Xuất dữ liệu người dùng thành công, file được lưu tại thư mục Downloads",
    "user_export_to_excel_fail": "Xuất dữ liệu người dùng thất bại!",
    "user_add_new_success": "Tạo người dùng mới thành công",
    "user_add_new_fail": "Tạo người dùng mới thất bại",
    "user_set_permission_success": "Phân quyền người dùng thành công",
    "user_set_permission_fail": "Phân quyền người dùng thất bại",
    "user_delete_success": "Xóa người dùng thành công",
    "user_delete_fail": "Xóa người dùng thất bại",
    "user_edit_success": "Cập nhật người dùng thành công",
    "user_edit_fail": "Cập nhật người dùng thất bại"
};

let organ_message = {
    // Data table header
    "table_header_name": "Tên tổ chức",
    "table_header_incharge": "Phụ trách",
    "table_header_domain": "Mã định danh",
    "table_header_email": "Địa chỉ email",
    "table_header_address": "Địa chỉ",
    "table_header_phonenumber": "Số điện thoại",
    // Config for user detail form
    "organ_table_header_name": "Tên tổ chức",
    "organ_table_header_incharge": "Phụ trách",
    "organ_table_header_domain": "Mã định danh",
    "organ_table_header_email": "Địa chỉ email",
    "organ_table_header_address": "Địa chỉ",
    "organ_table_header_phonenumber": "Số điện thoại",
    "organ_token": "Token",
    "organ_status": "Trạng thái",
    "organ_parent": "Đơn vị cha",
    "organ_token_change" : "Tạo token",
    "organ_token_revoke" : "Thu hồi",
    "organ_status_active": "Đang hoạt động",
    "organ_status_deactive" : "Ngừng hoạt động",
    "manage_remove_organ": "Xóa đơn vị",
    "manage_edit_organ": "Chỉnh sửa",
    "organ_import_from_excel_success": "Nhập dữ liệu đơn vị từ Excel thành công",
    "organ_import_invalid_format_file": "Sai định dạng file",
    "organ_import_from_excel_fail": "Nhập dữ liệu đơn vị thất bại",
    "organ_import_from_excel_conflic": "Dữ liệu bị trùng",
    "organ_import_from_excel_invalid_column": "File có thông tin cột không đúng!",
    "organ_export_to_excel_success": "Xuất dữ liệu đơn vị thành công, file được lưu tại thư mục Downloads",
    "organ_export_to_excel_fail": "Xuất dữ liệu đơn vị thất bại!",
    "organ_delete_success": "Xóa đơn vị thành công",
    "organ_delete_fail": "Xóa đơn vị thất bại",
    "organ_add_new_success": "Thêm mới đơn vị thành công",
    "organ_add_new_fail": "Thêm mới đơn vị thất bại",
    "organ_edit_success": "Cập nhật đơn vị thành công",
    "organ_edit_fail": "Cập nhật đơn vị thất bại",
    "organ_btn_confirm": "Cập nhật",
    "organ_btn_cancel": "Hủy"
};